name: buildify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.4
  dropdown_button2: ^2.3.9
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_database: ^11.1.4
  firebase_messaging: ^15.1.3
  firebase_remote_config: ^5.1.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_colorpicker: ^1.1.0
  flutter_dotenv: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.8.0
  get: ^4.6.6
  image_picker: ^1.1.2
  intl: ^0.19.0
  like_button: ^2.0.5
  loading_animation_widget: ^1.3.0
  markdown_widget: ^2.3.2+6
  material_design_icons_flutter: ^7.0.7296
  path_drawing: ^1.0.1
  shimmer: ^3.0.0
  step_progress_indicator: ^1.0.2
  syncfusion_flutter_core: ^27.1.57
  syncfusion_flutter_sliders: ^27.1.57


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
