// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsyhLQKiPCWS-jrUzomX7wtHlNpO3zPXs',
    appId: '1:1027457935560:web:6d1f7fe7101240f3875dfd',
    messagingSenderId: '1027457935560',
    projectId: 'buildify-x',
    authDomain: 'buildify-x.firebaseapp.com',
    storageBucket: 'buildify-x.firebasestorage.app',
    measurementId: 'G-47Y9WVBL3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPACzGp4_Lz8g2sKfo3hjf3shCedjvXWY',
    appId: '1:1027457935560:android:1941ce8d8fb8c6ac875dfd',
    messagingSenderId: '1027457935560',
    projectId: 'buildify-x',
    storageBucket: 'buildify-x.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHtFkoeof_sSRGZ8c5bR-mKm1F1PS9RxU',
    appId: '1:1027457935560:ios:0654b41c6e892526875dfd',
    messagingSenderId: '1027457935560',
    projectId: 'buildify-x',
    storageBucket: 'buildify-x.firebasestorage.app',
    iosBundleId: 'com.buildify.app',
  );
}
